package com.app.pojos;

public enum StateType {
	ANDHRA_PRADESH, ASSAM, ARUNACHAL_PRADESH, GUJRAT, BIHAR, HARYANA,
	HIMACHAL_PRADESH, JAMMU_KASHMIR, KARNATAKA, KERALA, MADHYA_PRADESH,
	MAHARASHTRA, MANIPUR, MEGHALAYA, MIZORAM, NAGALAND, ORISSA, PUNJAB, RAJASTHAN,
	SIKKIM, TAMIL_NADU, TRIPURA, UTTAR_PRADESH, WEST_BENGAL, DELHI, GOA,
	PONDICHERY, LAKSHDWEEP, DAMAN_DIU, DADRA_NAGAR, CHANDIGARH,
	ANDAMAN_NICOBAR, UTTARANCHAL, JHARKHAND, CHATTISGARH
}
